
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url:  <%= ENV['EXTERNAL_DB_URL'] %>

development:
  <<: *default
  database: budget_boss_development
  host: localhost
  port: 5432
  user: test
  password: test

test:
  <<: *default
  database: budget_boss_test
  port: 5432
  user: test
  password: test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  url: <%= ENV['EXTERNAL_DB_URL'] %>